# Generated by Django 3.2.1 on 2021-05-25 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coin', '0002_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='exchange',
            name='trade_url',
            field=models.CharField(default=1, max_length=255, verbose_name='link'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='exchange',
            name='image',
            field=models.CharField(max_length=255, null=True, verbose_name='Изображение биржи'),
        ),
    ]
