# Generated by Django 3.2.1 on 2021-05-13 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0002_comments_updated'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='comments',
            name='object_id',
        ),
    ]
