# Generated by Django 3.2.1 on 2021-05-15 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0005_auto_20210514_0716'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='user_parent',
            field=models.IntegerField(blank=True, null=True, verbose_name='Юсер коментария родителя'),
        ),
    ]
