version: '3'

services:
  pgdata:
    restart: always
    image: "postgres:13-alpine"
    ports:
        - "5432"
    volumes:
      - ./db_data/:/var/lib/postgresql/data/
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      # - DB_HOST=0.0.0.0
    networks:
      - backands_network


  djapi:
    restart: always
    build: ./scr
    depends_on:
      - pgdata
    command: gunicorn config.wsgi --bind 0.0.0.0:80
    # command: python manage.py runserver 0.0.0.0:8080 

    networks:
      - backands_network

  nginx:
    image: nginx:1.13
    restart: always
    volumes:
      - ./data/nginx:/etc/nginx/conf.d
    depends_on: 
      - djapi
    networks:
      - backands_network
    ports:
      - "80:80"
      - "443:443"
    

volumes:
  pgdata:  

networks:
  backands_network:
    driver: bridge