# Generated by Django 3.2.1 on 2021-05-14 07:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0003_auto_20210513_1939'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='parent_coment',
        ),
        migrations.AddField(
            model_name='comments',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='comment.comments', verbose_name='Родительский коментарий'),
        ),
    ]
