# Generated by Django 3.2.1 on 2021-06-02 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coin', '0004_alter_exchange_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coins',
            name='market_cap',
            field=models.IntegerField(blank=True, null=True, verbose_name='Капитализация'),
        ),
    ]
