# Generated by Django 3.2.1 on 2021-06-03 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coin', '0005_alter_coins_market_cap'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coins',
            name='price',
            field=models.FloatField(default=0, verbose_name='Цена монеты'),
        ),
    ]
