# Generated by Django 3.2.1 on 2021-06-03 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coin', '0006_alter_coins_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coins',
            name='market_cap',
            field=models.FloatField(blank=True, null=True, verbose_name='Капитализация'),
        ),
    ]
